COMP: Fix linker issues updating sqlite from 3.6.20 to 3.7.7.1
Error fixed by this commit is the following:

  /usr/bin/ld: ../../Libs/External/sqlite/libsqlite.a(sqlite3.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
  /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status

File copied from LuaDist/libsqlite3@0e30a6c
See https://github.com/LuaDist/libsqlite3